name: Sync Main to Bitbucket

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Bitbucket
        env:
          BITBUCKET_TOKEN: ${{ secrets.ATCTT3xFfGN0Cz7ojNV6GjLTi6SisyD2xPAfBfbwXXvwr6sPjV-XzM1oqkkeR0I13oT4V9o5XvtAxMiFk_DszIJxrnnQ1qU4WgGPqrNuLCaSUnL6VkD0OczKLp_g3Zem0p2J8Ngxqmiyl-3dOZSM-fYarcC6JlREbDeS81-lCE4Z8vIDWrEalHU=3D756947 }}
        run: |
          git remote add bitbucket https://x-token-auth:$ATCTT3xFfGN0Cz7ojNV6GjLTi6SisyD2xPAfBfbwXXvwr6sPjV-XzM1oqkkeR0I13oT4V9o5XvtAxMiFk_DszIJxrnnQ1qU4WgGPqrNuLCaSUnL6VkD0OczKLp_g3Zem0p2J8Ngxqmiyl-3dOZSM-fYarcC6JlREbDeS81-lCE4Z8vIDWrEalHU=3D756947@bitbucket.org/sltbd/talenthub_web_slt.git
          git push bitbucket main:main --force